### ISSUE TITLE
missing location status

### ISSUE THREAD

**Issue by matthewlent** [square/connect-java-sdk#30]
missing location status (active, inactive)

**Comment by yonpols** [comment]
Where do you see this missing? 
https://github.com/square/connect-java-sdk/blob/master/src/main/java/com/squareup/connect/models/Location.java#L1184

**Comment by matthewlent** [comment]
This is what I get when I use maven for the models/Location.java - note the
absence of the "status" field. Weirdly, it shows in the swagger source, but
not via maven.

<dependency>
  <groupId>com.squareup</groupId>
  <artifactId>connect</artifactId>
  <scope>compile</scope>
</dependency>


/*
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.squareup.connect.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.squareup.connect.models.Address;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents one of a business&#39;s locations.
 */
@ApiModel(description = "Represents one of a business's locations.")

public class Location {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("address")
  private Address address = null;

  @JsonProperty("timezone")
  private String timezone = null;

  /**
   * Gets or Sets capabilities
   */
  public enum CapabilitiesEnum {
    PROCESSING("CREDIT_CARD_PROCESSING");

    private String value;

    CapabilitiesEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CapabilitiesEnum fromValue(String text) {
      for (CapabilitiesEnum b : CapabilitiesEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("capabilities")
  private List<CapabilitiesEnum> capabilities = new
ArrayList<CapabilitiesEnum>();

  public Location id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The location's unique ID.
   * @return id
  **/
  @ApiModelProperty(value = "The location's unique ID.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Location name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The location's name.
   * @return name
  **/
  @ApiModelProperty(value = "The location's name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Location address(Address address) {
    this.address = address;
    return this;
  }

   /**
   * The location's physical address.
   * @return address
  **/
  @ApiModelProperty(value = "The location's physical address.")
  public Address getAddress() {
    return address;
  }

  public void setAddress(Address address) {
    this.address = address;
  }

  public Location timezone(String timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * The [IANA Timezone Database](https://www.iana.org/time-zones)
identifier for the location's timezone.
   * @return timezone
  **/
  @ApiModelProperty(value = "The [IANA Timezone
Database](https://www.iana.org/time-zones) identifier for the
location's timezone.")
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }

  public Location capabilities(List<CapabilitiesEnum> capabilities) {
    this.capabilities = capabilities;
    return this;
  }

  public Location addCapabilitiesItem(CapabilitiesEnum capabilitiesItem) {
    this.capabilities.add(capabilitiesItem);
    return this;
  }

   /**
   * Indicates which Square features are enabled for the location.
See [LocationCapability](#type-locationcapability) for possible
values.
   * @return capabilities
  **/
  @ApiModelProperty(value = "Indicates which Square features are
enabled for the location.  See
[LocationCapability](#type-locationcapability) for possible values.")
  public List<CapabilitiesEnum> getCapabilities() {
    return capabilities;
  }

  public void setCapabilities(List<CapabilitiesEnum> capabilities) {
    this.capabilities = capabilities;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Location location = (Location) o;
    return Objects.equals(this.id, location.id) &&
        Objects.equals(this.name, location.name) &&
        Objects.equals(this.address, location.address) &&
        Objects.equals(this.timezone, location.timezone) &&
        Objects.equals(this.capabilities, location.capabilities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, address, timezone, capabilities);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Location {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    capabilities:
").append(toIndentedString(capabilities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

**Comment by yonpols** [comment]
Can you confirm the version of SDK you're downloading? https://github.com/square/connect-java-sdk/blob/master/pom.xml#L8
