### ISSUE TITLE
i keep on getting an out of state error when ever i run the copy and paste example code

### ISSUE THREAD

**Issue by noname1997** [square/connect-java-sdk#39]
I have changed the setAccessToken to my token on my dev portal. Sorry very new to this. Is there something i need to replace "oauth2" with?

**Comment by StephenJosey** [comment]
Hi @noname1997 no need to be sorry, we all have to start somewhere 👍 

To better assist you, can you please provide a screenshot of the error that you're receiving? Also the example code you're referring to is the "Getting Started" in the README, correct?

**Comment by noname1997** [comment]
hello @StephenJosey thats correct its the README code where one lists the locations 

here is the error code,
![image](https://user-images.githubusercontent.com/40799411/42238298-513bde8a-7ece-11e8-9841-365daf040a35.png)

**Comment by StephenJosey** [comment]
@noname1997 are you using Maven to build the application? If so, did you already add:
```
<dependency>
    <groupId>com.squareup</groupId>
    <artifactId>connect</artifactId>
    <version>2.9.0</version>
    <scope>compile</scope>
</dependency>
```
to your pom.xml file? And run "mvn install"?

**Comment by noname1997** [comment]
@StephenJosey yup i have the correct maven dependency loaded in

**Comment by noname1997** [comment]
looks like is an issue with my proxy sorry

**Comment by StephenJosey** [comment]
@noname1997 no worries, I'm glad you figured it out! Please let us know if you have more questions in the future.
