### ISSUE TITLE
issue when build

### ISSUE THREAD

**Issue by hqkhanh9600196** [square/connect-java-sdk#55]
Results :

Tests in error:
  com.squareup.connect.api.CatalogApiTest: .\travis-ci\accounts.json
  com.squareup.connect.api.CheckoutApiTest: .\travis-ci\accounts.json
  com.squareup.connect.api.CustomersApiTest: .\travis-ci\accounts.json
  com.squareup.connect.api.LocationsApiTest: .\travis-ci\accounts.json
  com.squareup.connect.api.ReportingApiTest: .\travis-ci\accounts.json
  com.squareup.connect.api.TransactionsApiTest: .\travis-ci\accounts.json

Tests run: 17, Failures: 0, Errors: 6, Skipped: 9

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.389 s
[INFO] Finished at: 2019-02-28T17:26:03+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12:test (default-test) on project connect: There are test failures.
[ERROR]
[ERROR] Please refer to D:\data\mydoforms\connect-java-sdk-master\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[com.squareup.connect.api.LocationsApiTest.txt](https://github.com/square/connect-java-sdk/files/2914544/com.squareup.connect.api.LocationsApiTest.txt)
[com.squareup.connect.api.CustomersApiTest.txt](https://github.com/square/connect-java-sdk/files/2914545/com.squareup.connect.api.CustomersApiTest.txt)
[com.squareup.connect.api.ReportingApiTest.txt](https://github.com/square/connect-java-sdk/files/2914546/com.squareup.connect.api.ReportingApiTest.txt)
[com.squareup.connect.api.TransactionsApiTest.txt](https://github.com/square/connect-java-sdk/files/2914547/com.squareup.connect.api.TransactionsApiTest.txt)
[com.squareup.connect.api.CheckoutApiTest.txt](https://github.com/square/connect-java-sdk/files/2914548/com.squareup.connect.api.CheckoutApiTest.txt)
[com.squareup.connect.api.CatalogApiTest.txt](https://github.com/square/connect-java-sdk/files/2914549/com.squareup.connect.api.CatalogApiTest.txt)

**Comment by StephenJosey** [comment]
You need an `accounts.json` file in the `travis-ci` directory, did you create one? Also, could you clarify what you're trying to do? You do not need to build our SDK in order to use it. You should simply be able to install it via Maven or Gradle.

**Comment by hqkhanh9600196** [comment]
Hello StephenJosey,
Thank you for your answer. now it ok.
